### ISSUE TITLE
Bugs & a suggestion

### ISSUE THREAD

**Issue by Airshah** [KKiiya/BedWars-HotbarManager#1]
first bug:
when you buy a Tool item, for example Pickaxe, and you've set it as slot 5 in the Hotbar Manager, it will work correctly, but when we upgrade that to like Iron Pickaxe, it will no longer go to Slot 5 and it'll go to the first available slot.
second bug:
when for example someone buys a Axe, and it's set as slot 8 in the hotbar manager and they die, the axe will not go to slot 8 and instead it'll go to the first available slot.

Suggestion:
in the config.yml of the addon, there should be a feature that we can customize the items that could be modified in the hotbar manager, so we can for example change the category "Blocks" to "Wools" and also add & remove some categories

**Comment by KKiiya** [comment]
I see, thanks for the bug reports and the suggestions, I will leave this issue opened as a reminder and to also close it alongside the bugfixes and the features

**Comment by Airshah** [comment]
> I see, thanks for the bug reports and the suggestions, I will leave this issue opened as a reminder and to also close it alongside the bugfixes and the features

Any updates?

**Comment by KKiiya** [comment]
Added suggestions in version 1.4.0, the GUI is fully customizable now, apologies for the delayed reply.
