### ISSUE TITLE
how to build? 1.8.8

### ISSUE THREAD

**Issue by ghost** [KKiiya/BedWars-HotbarManager#5]

**Comment by KKiiya** [comment]
You need to have the API of spigot build tools, though I can add codemc repository so everyone can access it and build it with no problems

**Comment by unsnipeable** [comment]
can you add codemc repository?

**Comment by KKiiya** [comment]
I've shown how to build it in the main repo page, no difference between codemc and spigotmc. I've also tried adding it, no nms inside it
